// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzyxtvci_9c-ies-y_zTl5BO9SPn-teTc',
    appId: '1:161972570160:web:094589f65ffe4d018d45f5',
    messagingSenderId: '161972570160',
    projectId: 'mxh-tinavibe',
    authDomain: 'mxh-tinavibe.firebaseapp.com',
    storageBucket: 'mxh-tinavibe.appspot.com',
    measurementId: 'G-T4QHH9C6SZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmlYVZihpsV0LwqQ71on59FCVNrnPEBBA',
    appId: '1:161972570160:android:efcf8e9a91dc7b318d45f5',
    messagingSenderId: '161972570160',
    projectId: 'mxh-tinavibe',
    storageBucket: 'mxh-tinavibe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgovtziFi0X6ownYA5Hhdzky_QYDsDkrE',
    appId: '1:161972570160:ios:4b525eff2b50d6d78d45f5',
    messagingSenderId: '161972570160',
    projectId: 'mxh-tinavibe',
    storageBucket: 'mxh-tinavibe.appspot.com',
    iosClientId: '161972570160-is6bqjvpfr5o6jq7cm81nlns083umuuo.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirebaseMxhTinavibe',
  );
}
